<a href="https://colab.research.google.com/github/batra-ramit/DataScienceBootcamp/blob/master/Week2_HomeWork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problems

1) From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

2) Replace missing values in Min.Price and Max.Price columns with their respective mean (check documentation).
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

3) How to get the rows of a dataframe with row sum > 100?
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

4)Create a 4x4 NumPy array filled with random integers between 1 and 100. Then, reshape this array into two separate 2D arrays, where one represents the rows and the other represents the columns. Write a function, preferably using a lambda function, to calculate the sum of each row and each column separately, and return the results as two separate NumPy arrays

In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

rows=df.shape[0]

# Filter the 'Manufacturer', 'Model', and 'Type' columns for every 20th row starting from the 1st row (index 0)
result_df = df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]

# Display the result
print(result_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [7]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.head()

# Calculate the mean for 'Min.Price' and 'Max.Price' columns
min_price_mean = df['Min.Price'].mean()
max_price_mean = df['Max.Price'].mean()

# Replace missing values with the mean
df['Min.Price'].fillna(min_price_mean, inplace=True)
df['Max.Price'].fillna(max_price_mean, inplace=True)

# Display the modified DataFrame
print(df)



   Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31

In [9]:
import pandas as pd
import numpy as np

# Create a DataFrame with random integer values
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

# Filter rows with row sum > 100
result_df = df[df.sum(axis=1) > 100]

# Display the result
print(result_df)

     0   1   2   3
1   17  35  31  37
7   35  21  25  22
10  31  39  28  20
11  35  13  29  26
13  33  38  39  28
14  37  39  13  30


In [10]:
import numpy as np

# Create a 4x4 NumPy array filled with random integers between 1 and 100
random_array = np.random.randint(1, 101, size=(4, 4))

# Reshape the array into two separate 2D arrays (rows and columns)
rows_array = random_array.copy()
columns_array = random_array.T.copy()

# Define a lambda function to calculate the sum of each row
sum_rows = lambda arr: np.apply_along_axis(np.sum, axis=1, arr=arr)

# Define a lambda function to calculate the sum of each column
sum_columns = lambda arr: np.apply_along_axis(np.sum, axis=0, arr=arr)

# Calculate the sums using the lambda functions
sum_of_rows = sum_rows(rows_array)
sum_of_columns = sum_columns(columns_array)

# Display the results
print("Original Array:")
print(random_array)
print("\nRows Array:")
print(rows_array)
print("\nColumns Array:")
print(columns_array)
print("\nSum of Each Row:")
print(sum_of_rows)
print("\nSum of Each Column:")
print(sum_of_columns)


Original Array:
[[ 79  53  67  80]
 [ 85  88  35  66]
 [100  84  61  16]
 [ 60  55  98  33]]

Rows Array:
[[ 79  53  67  80]
 [ 85  88  35  66]
 [100  84  61  16]
 [ 60  55  98  33]]

Columns Array:
[[ 79  85 100  60]
 [ 53  88  84  55]
 [ 67  35  61  98]
 [ 80  66  16  33]]

Sum of Each Row:
[279 274 261 246]

Sum of Each Column:
[279 274 261 246]
